### ISSUE TITLE
Sidebar.Navmesh.js has an undefined var "Recast"

### ISSUE THREAD

**Issue by Druidhawk** [vincent/recastjs-editor#1]
Line 13 of https://github.com/vincent/recastjs-editor/blob/master/js/recastjs-editor/Sidebar.Navmesh.js has an undefined var "Recast"

```
this.recast = Recast;
```

**Comment by vincent** [comment]
Hi, thanks for your interest.

[Recast](https://github.com/vincent/recast.js) is indeed needed. I've added it as a dependency you can install by running `npm install` at the project root.
